---
- include: gocommon.yml

- name: "install build essentials"
  yum: name=zlib-devel state=present
  sudo: yes

- name: "install mongodb"
  yum: name=mongodb state=present
  sudo: yes

- name: "install mongodb-server"
  yum: name=mongodb-server state=present
  sudo: yes

- name: "ensure mongodb is running"
  service: name=mongod state=started enabled=yes
  sudo: yes

- file: path=/var/go owner=go group=go state=directory
  sudo: yes

- name: "install go-agent"
  yum: name=go-agent state=present
  sudo: yes

- name: "configuring go agent"
  sudo: yes
  shell: "sed -i 's/GO_SERVER=127.0.0.1/GO_SERVER={{go_server_ip}}/g' /etc/default/go-agent"

- name: "start go agent"
  service: name=go-agent state=started
  sudo: yes

- name: "install yum haskell stack repo"
  sudo: yes
  copy: src=files/fpco.repo dest=/etc/yum.repos.d/fpco.repo

- name: "install haskell stack"
  yum: name=stack state=present
  sudo: yes

- name: "install python 3.4"
  yum: name=python34 state=present
  sudo: yes

- name: "install python 3.4 dev"
  yum: name=python34-devel state=present
  sudo: yes

- name: "install pycrypto"
  yum: name=pycrypto state=present
  sudo: yes

- name: "install pip3"
  shell: "type pip3>/dev/null 2>&1 || (curl https://bootstrap.pypa.io/get-pip.py | /usr/bin/python3.4)"
  sudo: yes

- command: pip install virtualenv virtualenvwrapper
  sudo: yes
