---
- include: gocommon.yml

- name: "install go-server"
  yum: name=go-server state=latest
  sudo: yes

- name: "copy pipeline config"
  copy: src=files/cruise-config.xml dest=/etc/足go/cr足uise-足confi足g.xml
  sudo: yes

- name: "start go server"
  service: name=go-server state=started
  sudo: yes
