# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :goserver do |goserver|
    goserver.vm.box = "centos/7"
    goserver.vm.network "forwarded_port", guest: 8153, host: 8153
    goserver.vm.network "private_network", ip: "192.168.33.2"

    goserver.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end

    goserver.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/goserver_playbook.yml"
    end
  end

  config.vm.define :goagent do |goagent|
    goagent.vm.box = "centos/7"
    goagent.vm.network "forwarded_port", guest: 8153, host: 8153
    goagent.vm.network "private_network", ip: "192.168.33.2"

    goagent.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end

    goagent.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/goagent_playbook.yml"
    end
  end

  config.vm.define :app, primary: true do |app|
    app.vm.box = "centos/7"
    app.vm.network "forwarded_port", guest: 8153, host: 8153
    app.vm.network "private_network", ip: "192.168.33.2"

    app.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end

    app.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/app_playbook.yml"
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.limit = "all"
    ansible.playbook = "provisioning/common_playbook.yml"
  end

end
