# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :goserver do |goserver|
    goserver.vm.box = "centos/7"
    goserver.vm.hostname = "goserver.local"
    goserver.vm.network "forwarded_port", guest: 8153, host: 8153
    goserver.vm.network "private_network", ip: "192.168.33.2"

    goserver.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end

    goserver.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/goserver_playbook.yml"
    end
  end

  config.vm.define :goagent do |goagent|
    goagent.vm.box = "centos/7"
    goagent.vm.hostname = "goagent.local"
    # goagent.vm.network "forwarded_port", guest: 8153, host: 8153
    goagent.vm.network "private_network", ip: "192.168.33.3"

    goagent.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end

    goagent.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/goagent_playbook.yml"
    end
  end

  config.vm.define :app, primary: true do |app|
    app.vm.box = "centos/7"
    app.vm.hostname = "app.local"
    app.vm.network "forwarded_port", guest: 80, host: 8080
    app.vm.network "private_network", ip: "192.168.33.10"

    app.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end

    app.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/app_playbook.yml"
    end
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    # config.cache.scope = :machine
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

end
