baseUrl: http://localhost:8000
endpoints:
  - name: info
    url: /api/info
  - name: login
    url: /api/user/login
  - name: create_user
    url: /api/user/create
  - name: search_user
    url: /api/user/search
