---
- hosts: app
  vars:
    supervisord_config_file: /etc/supervisord.d/heub.ini
    app_home_path: /opt/heub
    nginx_site_config_path: /etc/nginx/conf.d/
  tasks:
  - include: tasks/common.yml

  - name: "install nginx"
    yum: name=nginx state=present
    sudo: yes

  - name: "copy app site nginx config"
    copy: src=files/heub.site.conf dest={{nginx_site_config_path}}
    sudo: yes

  - name: "fix SELinux permission issue for httpd"
    shell: "setsebool httpd_can_network_connect on -P"
    sudo: yes

  - name: "ensure ngix is running"
    service: name=nginx state=restarted enabled=yes
    sudo: yes

  - name: "copying app init.d config"
    copy: src=files/heub.init.d dest=/etc/init.d/heub
    sudo: yes

  - name: "create necessary app directories"
    shell: mkdir -p {{app_home_path}} && mkdir -p {{app_home_path}}/log && mkdir -p {{app_home_path}}/bin
    sudo: yes

  - name: "create necessary app directories"
    shell: mkdir -p /opt/fbeazt && mkdir -p /opt/fbeazt/log && mkdir -p /opt/fbeazt/bin
    sudo: yes

  - name: "install mongodb"
    yum: name=mongodb state=present
    sudo: yes

  - name: "install mongodb-server"
    yum: name=mongodb-server state=present
    sudo: yes

  - name: "ensure mongodb is running"
    service: name=mongod state=started enabled=yes
    sudo: yes

  - name: "install supervisor"
    yum: name=supervisor state=present
    sudo: yes

  - name: "create supervisor config"
    copy: src=files/supervisord.conf dest={{supervisord_config_file}}
    sudo: yes

  - name: "ensure supervisor is running"
    service: name=supervisord.service state=restarted enabled=yes
    sudo: yes

  - name: "install essentials"
    yum: name={{item}} state=present
    sudo: yes
    with_items:
      - gcc
      - gcc-c++
      - make
      - openssl-devel
      - pycrypto
      - python34
      - python34-devel
      - pymongo
      - setroubleshoot

  - command: semodule -i nginx.pp
    sudo: yes

  - name: "install pip3"
    shell: "type pip3>/dev/null 2>&1 || (curl https://bootstrap.pypa.io/get-pip.py | /usr/bin/python3.4)"
    sudo: yes

  - command: pip install virtualenv virtualenvwrapper
    sudo: yes

  handlers:
  - name: "restart nginx"
    service: name=nginx state=restarted
    sudo: yes
